# MoCap Analysis — Transform to TFrame Coordinate System

**Workflow:**
- `multiple_rigid_body.py` is loaded once via `importlib`.
- It runs its `__main__` block which produces `rb_dfs` and `st_time`.
- This notebook uses those DataFrames directly — no CSV re-read.

**Pipeline:**
1. Imports
2. Load script → get `rb_dfs` and `st_time`
3. Verify DataFrames are ready
4. Inspect raw data
5. Define and run coordinate frame transform
6. Sanity checks
7. Print noark m5 position in tframe (metres)
8. Print table m1–m5 positions in tframe (metres)
9. 2D trajectory plot — NOARK marker 5 in table frame

## Cell 1 — Imports

In [1]:
import importlib.util
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.spatial.transform import Rotation as R

print('Libraries loaded OK')

Libraries loaded OK

## Cell 2 — Load `multiple_rigid_body.py`

Walks up from the notebook directory to find the repo root,
then loads the script via `importlib`. The script's `__main__` block
runs automatically and populates `rb_dfs` and `st_time` into this
notebook's namespace.

In [2]:
import sys, importlib.util
from pathlib import Path

# ── locate this notebook's directory ─────────────────────────────────────────
try:
    _nb_file = Path(globals()['__vsc_ipynb_file__']).resolve()
    _nb_dir  = _nb_file.parent
except KeyError:
    _nb_dir = Path.cwd()

# ── walk up to find repo root ─────────────────────────────────────────────────
repo_root = _nb_dir
for candidate in [_nb_dir, *_nb_dir.parents]:
    if (candidate / 'vaideesh').exists() or (candidate / '.venv').exists():
        repo_root = candidate
        break

print(f'Repo root : {repo_root}')

# ── add script directory to sys.path so local imports inside the module work ──
_script_path = repo_root / 'vaideesh' / 'Analysis' / 'multiple_rigid_body.py'
assert _script_path.exists(), f'Script not found: {_script_path}'

_script_dir = str(_script_path.parent)
if _script_dir not in sys.path:
    sys.path.insert(0, _script_dir)

# ── load the module ───────────────────────────────────────────────────────────
spec = importlib.util.spec_from_file_location('multiple_rigid_body', _script_path)
mrb  = importlib.util.module_from_spec(spec)
sys.modules['multiple_rigid_body'] = mrb
spec.loader.exec_module(mrb)

# ── call the read function directly (since __main__ block doesn't run) ────────
FILE = "E:/Ragav/MS Bio Engineering/NOARK_backbone/mocap_data/table_frame.csv"

rb_dfs, st_time = mrb.read_3_rigid_body_csv(
    FILE,
    rb_names=["tframe", "noark", "table"],
)
rb_dfs = mrb.add_datetime_col_3rb(rb_dfs, st_time)
rb_dfs["tframe"], rb_dfs["noark"], rb_dfs["table"] = mrb.trunkate_3_dfs(
    rb_dfs["tframe"], rb_dfs["noark"], rb_dfs["table"], display_print=True
)

# ── bring helper functions into notebook namespace directly from mrb ───────────
add_datetime_col_3rb   = mrb.add_datetime_col_3rb
trunkate_3_dfs         = mrb.trunkate_3_dfs
get_rb_pos_cols        = mrb.get_rb_pos_cols
get_rb_rot_cols        = mrb.get_rb_rot_cols
get_rb_marker_name_3rb = mrb.get_rb_marker_name_3rb

print(f'Script loaded      : {_script_path}')
print(f'Capture start time : {st_time}')
print('rb_dfs keys        :', list(rb_dfs.keys()))

Repo root : E:\Ragav\MS Bio Engineering\NOARK_backbone
df_2 starts earlier, trimmed from index 0
df_2 ends later, trimmed to index 135
df_2 starts earlier, trimmed from index 0
df_2 ends later, trimmed to index 135
df_2 starts earlier, trimmed from index 0
df_2 ends later, trimmed to index 135
Script loaded      : E:\Ragav\MS Bio Engineering\NOARK_backbone\vaideesh\Analysis\multiple_rigid_body.py
Capture start time : 2026-04-17 17:06:12.485000
rb_dfs keys        : ['tframe', 'noark', 'table']

## Cell 3 — Verify DataFrames

The `__main__` block in `multiple_rigid_body.py` already calls
`add_datetime_col_3rb()` and `trunkate_3_dfs()`, so the DataFrames
are ready to use as-is. This cell just confirms their shapes and
that a `time` column is present.

In [3]:
print('DataFrames from multiple_rigid_body.py:')
print(f'{"Body":<10}  {"Shape":<15}  {"Has time col"}')
print('-' * 40)
for name, df in rb_dfs.items():
    has_time = 'time' in df.columns
    print(f'{name:<10}  {str(df.shape):<15}  {has_time}')

print('\nNaN rows per body:')
for name, df in rb_dfs.items():
    nan_rows = df.isna().any(axis=1).sum()
    print(f'  {name}: {nan_rows} NaN rows out of {len(df)}')

DataFrames from multiple_rigid_body.py:
Body        Shape            Has time col
----------------------------------------
tframe      (136, 27)        True
noark       (136, 31)        True
table       (136, 31)        True

NaN rows per body:
  tframe: 1 NaN rows out of 136
  noark: 1 NaN rows out of 136
  table: 1 NaN rows out of 136

## Cell 4 — Inspect raw DataFrames

In [5]:
print('── tframe ──')
display(rb_dfs['tframe'].head(30))

── tframe ──

,frame,seconds,tframe_rot_x,tframe_rot_y,tframe_rot_z,tframe_rot_w,tframe_pos_x,tframe_pos_y,tframe_pos_z,tframe_pos_err,...,tframe_marker_m2_mq,tframe_marker_m3_x,tframe_marker_m3_y,tframe_marker_m3_z,tframe_marker_m3_mq,tframe_marker_m4_x,tframe_marker_m4_y,tframe_marker_m4_z,tframe_marker_m4_mq,time
0,0,0.00,-0.000946,0.033981,-0.002022,-0.999420,0.074669,0.718711,0.482556,0.000779,...,0.735216,0.162471,0.641259,0.489042,0.913915,0.141485,0.789250,0.461756,0.843000,2026-04-17 17:06:12.485
1,1,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 17:06:12.495
2,2,0.02,-0.000786,0.034058,-0.001966,-0.999418,0.074670,0.718692,0.482578,0.000778,...,0.735000,0.162461,0.641232,0.489102,0.908744,0.141497,0.789217,0.461766,0.842706,2026-04-17 17:06:12.505
3,3,0.03,-0.000807,0.034119,-0.002065,-0.999415,0.074664,0.718668,0.482573,0.000825,...,0.735000,0.162469,0.641225,0.489104,0.908744,0.141479,0.789206,0.461771,0.842706,2026-04-17 17:06:12.515
4,4,0.04,-0.000799,0.034072,-0.002026,-0.999417,0.074666,0.718678,0.482580,0.000807,...,0.725718,0.162466,0.641228,0.489104,0.910754,0.141485,0.789211,0.461771,0.836358,2026-04-17 17:06:12.525
5,5,0.05,-0.000818,0.034103,-0.001972,-0.999416,0.074672,0.718693,0.482573,0.000793,...,0.731243,0.162464,0.641234,0.489100,0.908156,0.141500,0.789220,0.461772,0.839960,2026-04-17 17:06:12.535
6,6,0.06,-0.000847,0.034083,-0.001953,-0.999417,0.074673,0.718703,0.482569,0.000782,...,0.735011,0.162462,0.641240,0.489088,0.905613,0.141503,0.789229,0.461769,0.841366,2026-04-17 17:06:12.545
7,7,0.07,-0.000939,0.034003,-0.002055,-0.999419,0.074687,0.718735,0.482560,0.000758,...,0.735011,0.162493,0.641289,0.489051,0.905613,0.141498,0.789279,0.461762,0.841366,2026-04-17 17:06:12.555
8,8,0.08,-0.000895,0.034179,-0.001982,-0.999413,0.074668,0.718697,0.482565,0.000788,...,0.734625,0.162461,0.641239,0.489093,0.913158,0.141498,0.789229,0.461785,0.843855,2026-04-17 17:06:12.565
9,9,0.09,-0.000987,0.033827,-0.002011,-0.999425,0.074697,0.718712,0.482556,0.000794,...,0.735047,0.162499,0.641259,0.489009,0.913083,0.141507,0.789252,0.461741,0.850197,2026-04-17 17:06:12.575
10,10,0.10,-0.000846,0.034078,-0.001967,-0.999417,0.074674,0.718696,0.482575,0.000791,...,0.728792,0.162465,0.641235,0.489094,0.908175,0.141501,0.789223,0.461774,0.840236,2026-04-17 17:06:12.585
11,11,0.11,-0.000818,0.034093,-0.001972,-0.999416,0.074672,0.718679,0.482568,0.000772,...,0.728792,0.162464,0.641220,0.489093,0.908175,0.141500,0.789206,0.461765,0.840236,2026-04-17 17:06:12.595
12,12,0.12,-0.001052,0.034115,-0.002087,-0.999415,0.074679,0.718707,0.482542,0.000773,...,0.740182,0.162489,0.641266,0.489035,0.908898,0.141490,0.789260,0.461774,0.841624,2026-04-17 17:06:12.605
13,13,0.13,-0.000815,0.034126,-0.002011,-0.999415,0.074675,0.718683,0.482569,0.000778,...,0.739842,0.162472,0.641231,0.489101,0.908210,0.141498,0.789216,0.461770,0.840181,2026-04-17 17:06:12.615
14,14,0.14,0.000392,0.035521,-0.003450,-0.999363,0.074695,0.718246,0.482332,0.000435,...,0.886004,0.162689,0.641055,0.489303,0.932283,0.141379,0.788912,0.461543,0.821971,2026-04-17 17:06:12.625
15,15,0.15,-0.000932,0.033920,-0.002016,-0.999422,0.074681,0.718726,0.482565,0.000771,...,0.886004,0.162482,0.641273,0.489042,0.932283,0.141494,0.789264,0.461754,0.821971,2026-04-17 17:06:12.635
16,16,0.16,-0.000851,0.034116,-0.001954,-0.999416,0.074676,0.718692,0.482559,0.000766,...,0.738469,0.162465,0.641229,0.489083,0.914447,0.141507,0.789218,0.461764,0.843917,2026-04-17 17:06:12.645
17,17,0.17,-0.000856,0.033996,-0.001927,-0.999420,0.074675,0.718697,0.482579,0.000798,...,0.732375,0.162462,0.641229,0.489081,0.906854,0.141505,0.789219,0.461769,0.842375,2026-04-17 17:06:12.655
18,18,0.18,-0.000867,0.034093,-0.001974,-0.999416,0.074678,0.718703,0.482565,0.000770,...,0.744650,0.162470,0.641244,0.489082,0.904914,0.141505,0.789233,0.461769,0.843069,2026-04-17 17:06:12.665
19,19,0.19,-0.000931,0.033906,-0.002008,-0.999423,0.074674,0.718726,0.482563,0.000766,...,0.744650,0.162474,0.641273,0.489038,0.904914,0.141488,0.789263,0.461751,0.843069,2026-04-17 17:06:12.675
20,20,0.20,0.000390,0.035471,-0.003480,-0.999365,0.074692,0.718247,0.482325,0.000440,...,0.739234,0.162692,0.641062,0.489287,0.913517,0.141370,0.788917,0.461529,0.845613,2026-04-17 17:06:12.685
21,21,0.21,-0.000893,0.033881,-0.002037,-0.999423,0.074674,0.718724,0.482563,0.000768,...,0.736514,0.162479,0.641275,0.489039,0.915846,0.141483,0.789263,0.461742,0.846031,2026-04-17 17:06:12.695
22,22,0.22,0.000303,0.035370,-0.003551,-0.999368,0.074700,0.718268,0.482312,0.000419,...,0.889958,0.162713,0.641094,0.489244,0.936639,0.141364,0.788951,0.461515,0.830517,2026-04-17 17:06:12.705
23,23,0.23,-0.000870,0.034146,-0.001880,-0.999415,0.074659,0.718709,0.482577,0.000784,...,0.889958,0.162436,0.641233,0.489103,0.936639,0.141502,0.789226,0.461789,0.830517,2026-04-17 17:06:12.715
24,24,0.24,0.000380,0.035483,-0.003475,-0.999364,0.074704,0.718264,0.482325,0.000437,...,0.732399,0.162702,0.641078,0.489288,0.904371,0.141383,0.788935,0.461532,0.838113,2026-04-17 17:06:12.725
25,25,0.25,-0.000919,0.033912,-0.002045,-0.999422,0.074677,0.718723,0.482562,0.000759,...,0.736789,0.162482,0.641275,0.489040,0.915152,0.141486,0.789264,0.461749,0.846369,2026-04-17 17:06:12.735
26,26,0.26,-0.000786,0.034047,-0.001987,-0.999418,0.074667,0.718693,0.482573,0.000759,...,0.748273,0.162462,0.641236,0.489095,0.908813,0.141491,0.789220,0.461759,0.843116,2026-04-17 17:06:12.745
27,27,0.27,-0.000830,0.034078,-0.001967,-0.999417,0.074671,0.718694,0.482575,0.000795,...,0.727170,0.162462,0.641233,0.489096,0.906989,0.141498,0.789221,0.461772,0.840341,2026-04-17 17:06:12.755
28,28,0.28,0.000418,0.035540,-0.003458,-0.999362,0.074687,0.718252,0.482336,0.000441,...,0.727170,0.162682,0.641063,0.489315,0.906989,0.141371,0.788918,0.461546,0.840341,2026-04-17 17:06:12.765
29,29,0.29,-0.000902,0.033995,-0.001959,-0.999420,0.074683,0.718682,0.482561,0.000813,...,0.887029,0.162474,0.641220,0.489056,0.925592,0.141508,0.789212,0.461757,0.822356,2026-04-17 17:06:12.775

In [6]:
print('── noark ──')
display(rb_dfs['noark'].head(30))

── noark ──

,frame,seconds,noark_rot_x,noark_rot_y,noark_rot_z,noark_rot_w,noark_pos_x,noark_pos_y,noark_pos_z,noark_pos_err,...,noark_marker_m3_mq,noark_marker_m4_x,noark_marker_m4_y,noark_marker_m4_z,noark_marker_m4_mq,noark_marker_m5_x,noark_marker_m5_y,noark_marker_m5_z,noark_marker_m5_mq,time
0,0,0.00,0.026926,0.817206,-0.039622,-0.574352,0.552702,0.784215,0.488730,0.000673,...,0.930199,0.574371,0.772861,0.533571,0.736747,0.446474,0.839150,0.527338,0.837144,2026-04-17 17:06:12.485
1,1,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 17:06:12.495
2,2,0.02,0.026893,0.817219,-0.039707,-0.574329,0.552684,0.784215,0.488731,0.000683,...,0.929978,0.574353,0.772869,0.533574,0.740727,0.446447,0.839138,0.527329,0.832648,2026-04-17 17:06:12.505
3,3,0.03,0.026957,0.817191,-0.039627,-0.574371,0.552695,0.784230,0.488736,0.000683,...,0.929978,0.574365,0.772877,0.533577,0.740727,0.446472,0.839172,0.527347,0.832648,2026-04-17 17:06:12.515
4,4,0.04,0.026823,0.817234,-0.039666,-0.574314,0.552692,0.784212,0.488733,0.000678,...,0.927623,0.574360,0.772861,0.533576,0.736187,0.446449,0.839122,0.527335,0.833094,2026-04-17 17:06:12.525
5,5,0.05,0.026826,0.817216,-0.039804,-0.574330,0.552701,0.784237,0.488740,0.000669,...,0.934592,0.574373,0.772900,0.533584,0.737638,0.446452,0.839139,0.527335,0.840186,2026-04-17 17:06:12.535
6,6,0.06,0.026823,0.817236,-0.039660,-0.574311,0.552691,0.784232,0.488735,0.000676,...,0.930398,0.574358,0.772880,0.533577,0.737253,0.446448,0.839142,0.527336,0.836609,2026-04-17 17:06:12.545
7,7,0.07,0.026945,0.817215,-0.039526,-0.574345,0.552695,0.784231,0.488730,0.000676,...,0.930398,0.574361,0.772868,0.533570,0.737253,0.446475,0.839176,0.527342,0.836609,2026-04-17 17:06:12.555
8,8,0.08,0.026925,0.817216,-0.039671,-0.574334,0.552708,0.784236,0.488745,0.000687,...,0.928359,0.574376,0.772887,0.533588,0.735246,0.446477,0.839167,0.527345,0.835238,2026-04-17 17:06:12.565
9,9,0.09,0.026647,0.817223,-0.039061,-0.574379,0.552662,0.784339,0.488848,0.000729,...,0.861710,0.574330,0.772925,0.533674,0.745083,0.446446,0.839246,0.527526,0.884779,2026-04-17 17:06:12.575
10,10,0.10,0.026812,0.817241,-0.039719,-0.574299,0.552695,0.784221,0.488724,0.000672,...,0.930476,0.574363,0.772875,0.533568,0.736634,0.446447,0.839125,0.527319,0.837544,2026-04-17 17:06:12.585
11,11,0.11,0.026883,0.817241,-0.039645,-0.574302,0.552706,0.784242,0.488744,0.000688,...,0.930476,0.574370,0.772890,0.533588,0.736634,0.446468,0.839166,0.527341,0.837544,2026-04-17 17:06:12.595
12,12,0.12,0.026892,0.817232,-0.039684,-0.574312,0.552697,0.784232,0.488734,0.000676,...,0.920829,0.574363,0.772884,0.533578,0.734979,0.446459,0.839156,0.527329,0.836606,2026-04-17 17:06:12.605
13,13,0.13,0.026935,0.817211,-0.039665,-0.574341,0.552702,0.784228,0.488732,0.000673,...,0.929616,0.574370,0.772879,0.533574,0.736873,0.446472,0.839163,0.527333,0.835407,2026-04-17 17:06:12.615
14,14,0.14,0.026894,0.817237,-0.039591,-0.574311,0.552701,0.784244,0.488746,0.000695,...,0.920165,0.574366,0.772886,0.533588,0.735275,0.446469,0.839173,0.527348,0.833944,2026-04-17 17:06:12.625
15,15,0.15,0.026770,0.817284,-0.039566,-0.574252,0.552701,0.784229,0.488725,0.000669,...,0.920165,0.574362,0.772867,0.533568,0.735275,0.446454,0.839132,0.527322,0.833944,2026-04-17 17:06:12.635
16,16,0.16,0.026797,0.817276,-0.039707,-0.574252,0.552704,0.784228,0.488741,0.000682,...,0.931735,0.574367,0.772881,0.533587,0.737475,0.446451,0.839129,0.527325,0.837336,2026-04-17 17:06:12.645
17,17,0.17,0.026811,0.817245,-0.039716,-0.574295,0.552694,0.784231,0.488728,0.000680,...,0.929856,0.574361,0.772885,0.533572,0.734943,0.446445,0.839135,0.527322,0.833876,2026-04-17 17:06:12.655
18,18,0.18,0.026933,0.817241,-0.039536,-0.574308,0.552705,0.784218,0.488727,0.000665,...,0.931105,0.574368,0.772856,0.533569,0.748604,0.446479,0.839159,0.527330,0.835727,2026-04-17 17:06:12.665
19,19,0.19,0.026939,0.817194,-0.039680,-0.574364,0.552707,0.784219,0.488723,0.000673,...,0.931105,0.574378,0.772871,0.533564,0.748604,0.446479,0.839154,0.527328,0.835727,2026-04-17 17:06:12.675
20,20,0.20,0.026869,0.817240,-0.039617,-0.574306,0.552715,0.784229,0.488737,0.000682,...,0.928881,0.574380,0.772874,0.533580,0.733101,0.446479,0.839152,0.527338,0.836442,2026-04-17 17:06:12.685
21,21,0.21,0.026767,0.817259,-0.039766,-0.574274,0.552705,0.784230,0.488736,0.000677,...,0.923827,0.574371,0.772888,0.533582,0.735706,0.446447,0.839121,0.527324,0.839132,2026-04-17 17:06:12.695
22,22,0.22,0.026776,0.817269,-0.039691,-0.574264,0.552695,0.784222,0.488729,0.000675,...,0.929524,0.574359,0.772872,0.533574,0.730590,0.446442,0.839119,0.527319,0.839594,2026-04-17 17:06:12.705
23,23,0.23,0.026829,0.817257,-0.039606,-0.574284,0.552700,0.784216,0.488723,0.000675,...,0.929524,0.574363,0.772859,0.533566,0.730590,0.446458,0.839130,0.527321,0.839594,2026-04-17 17:06:12.715
24,24,0.24,0.026935,0.817224,-0.039546,-0.574330,0.552700,0.784230,0.488729,0.000674,...,0.931328,0.574365,0.772869,0.533570,0.734523,0.446476,0.839172,0.527337,0.837914,2026-04-17 17:06:12.725
25,25,0.25,0.026921,0.817206,-0.039653,-0.574349,0.552704,0.784220,0.488725,0.000671,...,0.928665,0.574373,0.772869,0.533566,0.737319,0.446474,0.839152,0.527330,0.835571,2026-04-17 17:06:12.735
26,26,0.26,0.026790,0.817275,-0.039598,-0.574262,0.552698,0.784224,0.488727,0.000676,...,0.929433,0.574360,0.772865,0.533571,0.728798,0.446451,0.839129,0.527323,0.838883,2026-04-17 17:06:12.745
27,27,0.27,0.027183,0.817163,-0.039490,-0.574410,0.552699,0.784258,0.488744,0.000684,...,0.922353,0.574366,0.772896,0.533583,0.739645,0.446508,0.839258,0.527360,0.828132,2026-04-17 17:06:12.755
28,28,0.28,0.026813,0.817230,-0.039711,-0.574316,0.552695,0.784226,0.488731,0.000680,...,0.922353,0.574364,0.772879,0.533574,0.739645,0.446449,0.839131,0.527330,0.828132,2026-04-17 17:06:12.765
29,29,0.29,0.026911,0.817225,-0.039574,-0.574329,0.552701,0.784229,0.488735,0.000677,...,0.929237,0.574367,0.772870,0.533577,0.736471,0.446473,0.839163,0.527342,0.834931,2026-04-17 17:06:12.775

In [8]:
print('── table ──')
display(rb_dfs['table'].head(30))

── table ──

,frame,seconds,table_rot_x,table_rot_y,table_rot_z,table_rot_w,table_pos_x,table_pos_y,table_pos_z,table_pos_err,...,table_marker_m3_mq,table_marker_m4_x,table_marker_m4_y,table_marker_m4_z,table_marker_m4_mq,table_marker_m5_x,table_marker_m5_y,table_marker_m5_z,table_marker_m5_mq,time
0,0,0.00,0.000710,0.002674,0.000164,-0.999996,0.186785,0.723478,0.904015,0.000970,...,0.431160,-0.321982,0.722480,1.214657,0.907083,0.664479,0.709349,0.473975,0.848946,2026-04-17 17:06:12.485
1,1,0.01,0.000584,0.002683,0.000171,-0.999996,0.186726,0.723366,0.904030,0.001117,...,0.443356,-0.322047,0.722296,1.214662,0.950930,0.664428,0.709338,0.473996,0.847106,2026-04-17 17:06:12.495
2,2,0.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 17:06:12.505
3,3,0.03,0.000744,0.002667,0.000137,-0.999996,0.186788,0.723490,0.904023,0.000968,...,0.443356,-0.321976,0.722485,1.214672,0.950930,0.664476,0.709357,0.473977,0.847106,2026-04-17 17:06:12.515
4,4,0.04,0.000629,0.002672,0.000173,-0.999996,0.186724,0.723373,0.904027,0.001118,...,0.431152,-0.322043,0.722334,1.214670,0.903163,0.664416,0.709304,0.473983,0.850733,2026-04-17 17:06:12.525
5,5,0.05,0.000715,0.002669,0.000148,-0.999996,0.186788,0.723496,0.904027,0.000975,...,0.430660,-0.321977,0.722484,1.214674,0.905098,0.664477,0.709377,0.473982,0.847499,2026-04-17 17:06:12.535
6,6,0.06,0.000719,0.002670,0.000166,-0.999996,0.186784,0.723487,0.904021,0.000971,...,0.430519,-0.321981,0.722496,1.214666,0.907416,0.664475,0.709348,0.473977,0.851750,2026-04-17 17:06:12.545
7,7,0.07,0.000741,0.002663,0.000166,-0.999996,0.186784,0.723486,0.904026,0.000970,...,0.430519,-0.321976,0.722509,1.214679,0.907416,0.664468,0.709328,0.473976,0.851750,2026-04-17 17:06:12.555
8,8,0.08,0.000706,0.002675,0.000159,-0.999996,0.186786,0.723497,0.904023,0.000973,...,0.433205,-0.321982,0.722491,1.214664,0.904540,0.664481,0.709375,0.473984,0.850281,2026-04-17 17:06:12.565
9,9,0.09,0.000704,0.002665,0.000169,-0.999996,0.186783,0.723492,0.904027,0.000971,...,0.434546,-0.321978,0.722495,1.214678,0.908310,0.664469,0.709363,0.473978,0.848389,2026-04-17 17:06:12.575
10,10,0.10,0.000714,0.002664,0.000158,-0.999996,0.186780,0.723488,0.904024,0.000971,...,0.435465,-0.321981,0.722486,1.214675,0.906068,0.664466,0.709361,0.473975,0.849649,2026-04-17 17:06:12.585
11,11,0.11,0.000715,0.002666,0.000172,-0.999996,0.186786,0.723488,0.904019,0.000969,...,0.435465,-0.321977,0.722500,1.214669,0.906068,0.664473,0.709347,0.473972,0.849649,2026-04-17 17:06:12.595
12,12,0.12,0.000698,0.002671,0.000176,-0.999996,0.186781,0.723496,0.904024,0.000967,...,0.433144,-0.321985,0.722502,1.214668,0.906906,0.664472,0.709365,0.473981,0.849774,2026-04-17 17:06:12.605
13,13,0.13,0.000712,0.002670,0.000165,-0.999996,0.186785,0.723509,0.904028,0.000973,...,0.432514,-0.321980,0.722512,1.214673,0.908762,0.664475,0.709376,0.473984,0.848980,2026-04-17 17:06:12.615
14,14,0.14,0.000726,0.002664,0.000148,-0.999996,0.186791,0.723506,0.904031,0.000971,...,0.431788,-0.321970,0.722501,1.214683,0.905117,0.664476,0.709377,0.473982,0.847784,2026-04-17 17:06:12.625
15,15,0.15,0.000682,0.002675,0.000162,-0.999996,0.186792,0.723486,0.904030,0.000973,...,0.431788,-0.321976,0.722469,1.214671,0.905117,0.664486,0.709383,0.473990,0.847784,2026-04-17 17:06:12.635
16,16,0.16,0.000741,0.002664,0.000166,-0.999996,0.186782,0.723485,0.904016,0.000966,...,0.429775,-0.321980,0.722508,1.214668,0.907828,0.664466,0.709327,0.473967,0.848481,2026-04-17 17:06:12.645
17,17,0.17,0.000710,0.002673,0.000149,-0.999996,0.186778,0.723504,0.904024,0.000975,...,0.434471,-0.321988,0.722491,1.214667,0.906678,0.664472,0.709387,0.473983,0.847062,2026-04-17 17:06:12.655
18,18,0.18,0.000738,0.002660,0.000170,-0.999996,0.186775,0.723489,0.904018,0.000969,...,0.439535,-0.321984,0.722514,1.214674,0.905698,0.664457,0.709329,0.473966,0.849155,2026-04-17 17:06:12.665
19,19,0.19,0.000703,0.002673,0.000153,-0.999996,0.186790,0.723497,0.904023,0.000975,...,0.439535,-0.321977,0.722483,1.214666,0.905698,0.664483,0.709383,0.473982,0.849155,2026-04-17 17:06:12.675
20,20,0.20,0.000752,0.002662,0.000141,-0.999996,0.186779,0.723494,0.904014,0.000969,...,0.429889,-0.321981,0.722498,1.214668,0.906463,0.664463,0.709350,0.473963,0.848518,2026-04-17 17:06:12.685
21,21,0.21,0.000679,0.002676,0.000161,-0.999996,0.186783,0.723502,0.904022,0.000979,...,0.432759,-0.321986,0.722482,1.214661,0.909232,0.664479,0.709402,0.473983,0.846880,2026-04-17 17:06:12.695
22,22,0.22,0.000643,0.002626,0.000204,-0.999996,0.186751,0.723563,0.904045,0.000900,...,0.511289,-0.321987,0.722564,1.214736,0.894107,0.664402,0.709453,0.473957,0.826350,2026-04-17 17:06:12.705
23,23,0.23,0.000689,0.002675,0.000180,-0.999996,0.186787,0.723495,0.904021,0.000975,...,0.511289,-0.321981,0.722500,1.214662,0.894107,0.664482,0.709368,0.473981,0.826350,2026-04-17 17:06:12.715
24,24,0.24,0.000619,0.002621,0.000205,-0.999996,0.186739,0.723552,0.904043,0.000895,...,0.429269,-0.321996,0.722538,1.214738,0.909366,0.664386,0.709461,0.473950,0.848994,2026-04-17 17:06:12.725
25,25,0.25,0.000697,0.002672,0.000167,-0.999996,0.186786,0.723506,0.904021,0.000966,...,0.431534,-0.321980,0.722503,1.214664,0.908253,0.664478,0.709384,0.473979,0.849044,2026-04-17 17:06:12.735
26,26,0.26,0.000715,0.002675,0.000159,-0.999996,0.186789,0.723498,0.904021,0.000969,...,0.430094,-0.321979,0.722498,1.214662,0.906507,0.664483,0.709368,0.473982,0.849363,2026-04-17 17:06:12.745
27,27,0.27,0.000683,0.002671,0.000167,-0.999996,0.186786,0.723496,0.904025,0.000971,...,0.430897,-0.321979,0.722483,1.214670,0.908312,0.664477,0.709387,0.473981,0.849023,2026-04-17 17:06:12.755
28,28,0.28,0.000733,0.002672,0.000167,-0.999996,0.186788,0.723509,0.904021,0.000970,...,0.430897,-0.321978,0.722529,1.214665,0.908312,0.664480,0.709356,0.473980,0.849023,2026-04-17 17:06:12.765
29,29,0.29,0.000604,0.002687,0.000175,-0.999996,0.186734,0.723393,0.904028,0.001117,...,0.431609,-0.322041,0.722341,1.214656,0.906488,0.664439,0.709344,0.473997,0.849525,2026-04-17 17:06:12.775

## Cell 5 — Define `transform_to_tframe()`

**Coordinate frame construction (per frame, from mocap marker positions):**

| Step | Detail |
|---|---|
| Origin | `tframe_marker_1` position in mocap frame |
| X axis | `tframe_marker_3 − origin`, normalised |
| Y axis | `tframe_marker_2 − origin`, Gram-Schmidt orthogonalised then normalised |
| Z axis | `X × Y` (right-handed) |
| Translation reference | `tframe_marker_3` → becomes **(0, 0, 0)** in table frame |

**Transform formula:** `p_table = R_mocap2table.T @ (p_mocap − t_mocap)`  
where `R_mocap2table` columns are `[vxnorm, vynorm, vznorm]` and `t_mocap = tvec(tframe_marker_3)`.

**Units:** Motive exports positions in **metres** — no conversion needed.  
**Column suffix `_m`** makes the unit explicit in every position column.

In [ ]:
def transform_to_tframe(rb_dfs):
    tframe_df = rb_dfs['tframe'].copy()
    noark_df  = rb_dfs['noark'].copy()
    table_df  = rb_dfs['table'].copy()

    # ── Per-frame: build table coordinate frame from tframe marker positions ──
    # marker positions are already in mocap (world) frame
    m1 = tframe_df[['tframe_marker_m1_x', 'tframe_marker_m1_y', 'tframe_marker_m1_z']].values.astype(float)
    m2 = tframe_df[['tframe_marker_m2_x', 'tframe_marker_m2_y', 'tframe_marker_m2_z']].values.astype(float)
    m3 = tframe_df[['tframe_marker_m3_x', 'tframe_marker_m3_y', 'tframe_marker_m3_z']].values.astype(float)

    # Origin of table frame = tframe_marker_1 (in mocap frame)
    org = m1                             # shape (N, 3)

    # X direction: marker_3 − origin
    v1 = m3 - org

    # Y direction: marker_2 − origin
    v2 = m2 - org

    # Gram-Schmidt orthonormalisation
    vxnorm  = v1 / np.linalg.norm(v1, axis=1, keepdims=True)          # X unit vector
    vycap   = v2 - np.sum(v2 * vxnorm, axis=1, keepdims=True) * vxnorm
    vynorm  = vycap / np.linalg.norm(vycap, axis=1, keepdims=True)    # Y unit vector
    vznorm  = np.cross(vxnorm, vynorm)                                 # Z = X × Y (right-handed)

    # R_mocap2table: shape (N, 3, 3)  — columns are [vx, vy, vz] in mocap frame
    # R.T = R^{-1} rotates FROM mocap TO table
    mocap_rot_mat = np.stack([vxnorm, vynorm, vznorm], axis=-1)        # (N, 3, 3)

    # Translation vector: tframe_marker_3 is the TABLE FRAME ORIGIN in mocap frame
    mocap_tvec_vec = m3                                                 # shape (N, 3)

    # ── Helper: transform a (N,3) array of mocap positions to table frame ────
    def pos_to_tframe(p_mocap):
        # p_table = R.T @ (p_mocap − t)
        # einsum: for each row i: R[i].T @ (p_mocap[i] - t[i])
        delta = p_mocap - mocap_tvec_vec                               # (N, 3)
        return np.einsum('nij,nj->ni', mocap_rot_mat.transpose(0, 2, 1), delta)  # (N, 3)

    # ── noark ─────────────────────────────────────────────────────────────────
    quat_cols_noark = ['noark_rot_x', 'noark_rot_y', 'noark_rot_z', 'noark_rot_w']
    quat_cols_table = ['table_rot_x', 'table_rot_y', 'table_rot_z', 'table_rot_w']

    noark_result = pd.DataFrame({
        'frame'  : noark_df['frame'].values,
        'seconds': noark_df['seconds'].values,
        'time'   : noark_df['time'].values,
    })

    p_m5    = noark_df[['noark_marker_m5_x',
                         'noark_marker_m5_y',
                         'noark_marker_m5_z']].values.astype(float)
    p_m5_tf = pos_to_tframe(p_m5)
    noark_result['noark_m5_tf_x_m'] = p_m5_tf[:, 0]
    noark_result['noark_m5_tf_y_m'] = p_m5_tf[:, 1]
    noark_result['noark_m5_tf_z_m'] = p_m5_tf[:, 2]

    # ── table ─────────────────────────────────────────────────────────────────
    table_result = pd.DataFrame({
        'frame'  : table_df['frame'].values,
        'seconds': table_df['seconds'].values,
        'time'   : table_df['time'].values,
    })

    for i in range(1, 6):
        p_world     = table_df[[f'table_marker_m{i}_x',
                                 f'table_marker_m{i}_y',
                                 f'table_marker_m{i}_z']].values.astype(float)
        p_tf_coords = pos_to_tframe(p_world)
        table_result[f'table_m{i}_tf_x_m'] = p_tf_coords[:, 0]
        table_result[f'table_m{i}_tf_y_m'] = p_tf_coords[:, 1]
        table_result[f'table_m{i}_tf_z_m'] = p_tf_coords[:, 2]

    return {
        'noark_in_tframe': noark_result.reset_index(drop=True),
        'table_in_tframe': table_result.reset_index(drop=True),
        # expose for sanity checks
        '_mocap_rot_mat' : mocap_rot_mat,
        '_mocap_tvec_vec': mocap_tvec_vec,
        '_tframe_m3_mocap': m3,
    }

## Cell 6 — Run the transformation

In [ ]:
tframe_dfs = transform_to_tframe(rb_dfs)

print('noark_in_tframe shape :', tframe_dfs['noark_in_tframe'].shape)
print('table_in_tframe shape :', tframe_dfs['table_in_tframe'].shape)
print('\nnoark_in_tframe columns:')
print(tframe_dfs['noark_in_tframe'].columns.tolist())
print('\ntable_in_tframe columns:')
print(tframe_dfs['table_in_tframe'].columns.tolist())

## Cell 7 — Inspect transformed DataFrames

In [ ]:
print('── noark in tframe ──')
display(tframe_dfs['noark_in_tframe'].head())

In [ ]:
print('── table in tframe ──')
display(tframe_dfs['table_in_tframe'].head())

## Cell 8 — Sanity checks

In [ ]:
# ── Sanity checks for marker-based table frame transform ─────────────────────

tframe_extras = tframe_dfs   # includes _mocap_rot_mat, _mocap_tvec_vec, _tframe_m3_mocap

mocap_rot_mat   = tframe_extras['_mocap_rot_mat']    # (N, 3, 3)
mocap_tvec_vec  = tframe_extras['_mocap_tvec_vec']   # (N, 3)  = tframe_marker_3
tframe_m3_mocap = tframe_extras['_tframe_m3_mocap']  # (N, 3)

# ── Check 1: tframe_marker_3 (origin) transforms to (0, 0, 0) ────────────────
delta_m3    = tframe_m3_mocap - mocap_tvec_vec        # should be all zeros
p_m3_tf     = np.einsum('nij,nj->ni',
                          mocap_rot_mat.transpose(0, 2, 1),
                          delta_m3)
max_pos_err = np.nanmax(np.abs(p_m3_tf))
print(f'Check 1 — tframe_marker_3 → (0,0,0) : max error = {max_pos_err:.2e} m  →  {"PASS ✓" if max_pos_err < 1e-10 else "FAIL ✗"}')

# ── Check 2: rotation matrix columns are unit vectors ────────────────────────
col_norms = np.linalg.norm(mocap_rot_mat, axis=1)     # (N, 3)  norms of each column
max_norm_err = np.nanmax(np.abs(col_norms - 1.0))
print(f'Check 2 — R columns are unit vectors : max deviation = {max_norm_err:.2e}  →  {"PASS ✓" if max_norm_err < 1e-6 else "FAIL ✗"}')

# ── Check 3: rotation matrix is orthogonal (R.T @ R ≈ I) ────────────────────
RtR       = np.einsum('nij,njk->nik',
                       mocap_rot_mat.transpose(0, 2, 1),
                       mocap_rot_mat)                  # (N, 3, 3)
identity  = np.eye(3)[None].repeat(len(RtR), axis=0)
max_orth_err = np.nanmax(np.abs(RtR - identity))
print(f'Check 3 — R.T @ R = I (orthogonality) : max deviation = {max_orth_err:.2e}  →  {"PASS ✓" if max_orth_err < 1e-6 else "FAIL ✗"}')

# ── Check 4: right-handedness det(R) ≈ +1 ───────────────────────────────────
dets    = np.linalg.det(mocap_rot_mat)
max_det_err = np.nanmax(np.abs(dets - 1.0))
print(f'Check 4 — det(R) = +1 (right-handed)  : max deviation = {max_det_err:.2e}  →  {"PASS ✓" if max_det_err < 1e-6 else "FAIL ✗"}')

print(f'\n(checked over {len(mocap_rot_mat)} frames)')

In [ ]:
# (Quaternion-norm check removed — new transform is purely positional/marker-based,
#  no quaternion output is produced. Add orientation output here if needed later.)
print('No quaternion output in this transform — skipping norm check.')

## Cell 9 — noark m5 position in tframe (metres)

In [ ]:
# Cell 9 — noark m5
df_n = tframe_dfs['noark_in_tframe']
print('noark Marker 5 — position in tframe coordinate system (metres)')
print(df_n[['frame','seconds','noark_m5_tf_x_m','noark_m5_tf_y_m','noark_m5_tf_z_m']].to_string(index=False))
print('\nSummary statistics (metres):')
display(df_n[['noark_m5_tf_x_m','noark_m5_tf_y_m','noark_m5_tf_z_m']].describe().round(6))

## Cell 10 — Table marker m1–m5 positions in tframe (metres)

In [ ]:
# Cell 10 — table m1–m5
df_t = tframe_dfs['table_in_tframe']
for i in range(1, 6):
    cols = [f'table_m{i}_tf_x_m', f'table_m{i}_tf_y_m', f'table_m{i}_tf_z_m']
    print(f'\ntable Marker {i} — position in tframe coordinate system (metres)')
    print(df_t[['frame','seconds'] + cols].to_string(index=False))
    print(f'\nSummary statistics — Marker {i} (metres):')
    display(df_t[cols].describe().round(6))

## Cell 11 — 2D Trajectory of NOARK Marker 5 in Table Frame

Plots X–Y position of `noark_marker_m5` in the table coordinate frame.  
- **Colour** encodes time progression (blue → early, red → late).  
- **▲ triangles** mark the four table-corner reference points (P1–P4) derived from `table_m1–m4` mean positions.  
- Axes are converted to **cm** for readability.

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np

# ── pull data ─────────────────────────────────────────────────────────────────
df_n = tframe_dfs['noark_in_tframe'].copy()
df_t = tframe_dfs['table_in_tframe'].copy()

# convert m → cm
x_cm = df_n['noark_m5_tf_x_m'].values * 100.0
y_cm = df_n['noark_m5_tf_y_m'].values * 100.0

# ── colour map: time progression ─────────────────────────────────────────────
t_norm = (np.arange(len(x_cm)) / max(len(x_cm) - 1, 1))   # 0 → 1

# ── table corner reference points (mean over all frames, m → cm) ─────────────
corner_labels = ['P1', 'P2', 'P3', 'P4']
corner_xy = []
for i in range(1, 5):
    cx = df_t[f'table_m{i}_tf_x_m'].mean() * 100.0
    cy = df_t[f'table_m{i}_tf_y_m'].mean() * 100.0
    corner_xy.append((cx, cy))

# ── plot ──────────────────────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(10, 5))

sc = ax.scatter(
    x_cm, y_cm,
    c=t_norm,
    cmap='coolwarm',
    s=18,
    alpha=0.75,
    zorder=2,
    label='NOARK m5 (MoCap)',
)

# colourbar
cbar = fig.colorbar(sc, ax=ax, pad=0.02, fraction=0.03)
cbar.set_label('Time progression  (0 = start, 1 = end)', fontsize=9)

# table corner markers
for (cx, cy), lbl in zip(corner_xy, corner_labels):
    ax.plot(cx, cy, marker='^', markersize=12, color='black', zorder=5)
    ax.annotate(
        lbl,
        xy=(cx, cy),
        xytext=(0, 8),
        textcoords='offset points',
        ha='center', va='bottom',
        fontsize=9, fontweight='bold',
    )

ax.set_xlabel('X (cm)', fontsize=11)
ax.set_ylabel('Y (cm)', fontsize=11)
ax.set_title('2D Trajectory of NOARK Marker 5 in Table Frame', fontsize=13)
ax.legend(loc='lower right', fontsize=9)
ax.set_aspect('equal')
ax.grid(True, linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()

print(f'\nTrajectory extents:')
print(f'  X : {x_cm.min():.1f} → {x_cm.max():.1f} cm  (range {x_cm.max()-x_cm.min():.1f} cm)')
print(f'  Y : {y_cm.min():.1f} → {y_cm.max():.1f} cm  (range {y_cm.max()-y_cm.min():.1f} cm)')
print(f'  N frames plotted: {len(x_cm)}')